#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-internals-make_options_for_nnn.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
futurize:::testme("internals-make_options_for_nnn")
