#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-futurize-future.apply.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
futurize:::testme("futurize-future.apply")
