#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-future.apply-future_Filter.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
futurize:::testme("future.apply-future_Filter")
