#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-futurize-Sim.DiffProc.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
futurize:::testme("futurize-Sim.DiffProc")
