## This runs testme test script inst/testme/test-doFuture-foreach_dofuture,nested_colon.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
futurize:::testme("doFuture-foreach_dofuture,nested_colon")
