#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-doFuture-foreach_dofuture,errors.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
futurize:::testme("doFuture-foreach_dofuture,errors")
