## This runs testme test script inst/testme/test-future.apply-future_lapply,globals.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
futurize:::testme("future.apply-future_lapply,globals")
