---
title: "Parallelize base-R functions"
author: "Henrik Bengtsson"
date: "2025-08-23"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Parallelize base-R functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# TL;DR

```r
library(futurize)
plan(multisession)

xs <- 1:1000
y <- lapply(xs, slow_fcn) |> futurize()
```

# Introduction

The **futurize** package allows you to easily turn sequential code
into parallel code by piping the sequential code to the `futurize()`
function. Easy!

This vignette demonstrates how use this approach to parallelize base-R
functions such as `lapply()`, `tapply()`, `apply()`, `replicate()`,
and `kernapply()` in the **stats** package.


# Background

The base R `lapply()` function is commonly used to apply a function to
the elements of a vector or a list. For example, 

```r
xs <- 1:1000
y <- lapply(xs, slow_fcn)
```

Here `lapply()` evaluates sequentially, but we can easily make it to
evaluate parallelly, by using:

```r
y <- lapply(xs, slow_fcn) |> futurize()
```

This will distribute the calculations across the available workers
assuming that we first have set them up as:

```r
library(futurize)
plan(multisession)
```


# Supported Functions

The `futurize()` function supports parallelization of the common base
R functions. From the **base** package, the following functions are
supported:

 * `apply()`
 * `by()`
 * `eapply()`
 * `Filter()`
 * `lapply()`
 * `Map()`
 * `mapply()`
 * `.mapply()`
 * `replicate()`
 * `sapply()`
 * `tapply()`
 * `vapply()`

The `rapply()` function is not supported by `futurize()`.

From the **stats** package, the following functions are supported:

 * `kernapply()`


# Notes

 * Not all functions passed to `apply()` are guaranteed to be safe for
   parallelization. Ensure that the function is side-effect free and
   does not depend on external state.
